/*
Hautech API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hautechapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AttachAccessControllerParamsDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AttachAccessControllerParamsDto{}

// AttachAccessControllerParamsDto struct for AttachAccessControllerParamsDto
type AttachAccessControllerParamsDto struct {
	ParentResourceId string `json:"parentResourceId"`
}

type _AttachAccessControllerParamsDto AttachAccessControllerParamsDto

// NewAttachAccessControllerParamsDto instantiates a new AttachAccessControllerParamsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttachAccessControllerParamsDto(parentResourceId string) *AttachAccessControllerParamsDto {
	this := AttachAccessControllerParamsDto{}
	this.ParentResourceId = parentResourceId
	return &this
}

// NewAttachAccessControllerParamsDtoWithDefaults instantiates a new AttachAccessControllerParamsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttachAccessControllerParamsDtoWithDefaults() *AttachAccessControllerParamsDto {
	this := AttachAccessControllerParamsDto{}
	return &this
}

// GetParentResourceId returns the ParentResourceId field value
func (o *AttachAccessControllerParamsDto) GetParentResourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ParentResourceId
}

// GetParentResourceIdOk returns a tuple with the ParentResourceId field value
// and a boolean to check if the value has been set.
func (o *AttachAccessControllerParamsDto) GetParentResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParentResourceId, true
}

// SetParentResourceId sets field value
func (o *AttachAccessControllerParamsDto) SetParentResourceId(v string) {
	o.ParentResourceId = v
}

func (o AttachAccessControllerParamsDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AttachAccessControllerParamsDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["parentResourceId"] = o.ParentResourceId
	return toSerialize, nil
}

func (o *AttachAccessControllerParamsDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"parentResourceId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAttachAccessControllerParamsDto := _AttachAccessControllerParamsDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAttachAccessControllerParamsDto)

	if err != nil {
		return err
	}

	*o = AttachAccessControllerParamsDto(varAttachAccessControllerParamsDto)

	return err
}

type NullableAttachAccessControllerParamsDto struct {
	value *AttachAccessControllerParamsDto
	isSet bool
}

func (v NullableAttachAccessControllerParamsDto) Get() *AttachAccessControllerParamsDto {
	return v.value
}

func (v *NullableAttachAccessControllerParamsDto) Set(val *AttachAccessControllerParamsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableAttachAccessControllerParamsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableAttachAccessControllerParamsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttachAccessControllerParamsDto(val *AttachAccessControllerParamsDto) *NullableAttachAccessControllerParamsDto {
	return &NullableAttachAccessControllerParamsDto{value: val, isSet: true}
}

func (v NullableAttachAccessControllerParamsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttachAccessControllerParamsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


