/*
Hautech API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hautechapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListPosesDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListPosesDto{}

// ListPosesDto struct for ListPosesDto
type ListPosesDto struct {
	Data []PoseEntity `json:"data"`
	PageInfo ListAccountsDtoPageInfo `json:"pageInfo"`
}

type _ListPosesDto ListPosesDto

// NewListPosesDto instantiates a new ListPosesDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPosesDto(data []PoseEntity, pageInfo ListAccountsDtoPageInfo) *ListPosesDto {
	this := ListPosesDto{}
	this.Data = data
	this.PageInfo = pageInfo
	return &this
}

// NewListPosesDtoWithDefaults instantiates a new ListPosesDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPosesDtoWithDefaults() *ListPosesDto {
	this := ListPosesDto{}
	return &this
}

// GetData returns the Data field value
func (o *ListPosesDto) GetData() []PoseEntity {
	if o == nil {
		var ret []PoseEntity
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListPosesDto) GetDataOk() ([]PoseEntity, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListPosesDto) SetData(v []PoseEntity) {
	o.Data = v
}

// GetPageInfo returns the PageInfo field value
func (o *ListPosesDto) GetPageInfo() ListAccountsDtoPageInfo {
	if o == nil {
		var ret ListAccountsDtoPageInfo
		return ret
	}

	return o.PageInfo
}

// GetPageInfoOk returns a tuple with the PageInfo field value
// and a boolean to check if the value has been set.
func (o *ListPosesDto) GetPageInfoOk() (*ListAccountsDtoPageInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageInfo, true
}

// SetPageInfo sets field value
func (o *ListPosesDto) SetPageInfo(v ListAccountsDtoPageInfo) {
	o.PageInfo = v
}

func (o ListPosesDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListPosesDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["pageInfo"] = o.PageInfo
	return toSerialize, nil
}

func (o *ListPosesDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"pageInfo",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListPosesDto := _ListPosesDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListPosesDto)

	if err != nil {
		return err
	}

	*o = ListPosesDto(varListPosesDto)

	return err
}

type NullableListPosesDto struct {
	value *ListPosesDto
	isSet bool
}

func (v NullableListPosesDto) Get() *ListPosesDto {
	return v.value
}

func (v *NullableListPosesDto) Set(val *ListPosesDto) {
	v.value = val
	v.isSet = true
}

func (v NullableListPosesDto) IsSet() bool {
	return v.isSet
}

func (v *NullableListPosesDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPosesDto(val *ListPosesDto) *NullableListPosesDto {
	return &NullableListPosesDto{value: val, isSet: true}
}

func (v NullableListPosesDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListPosesDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


