/*
Hautech API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hautechapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpscaleV1Input type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpscaleV1Input{}

// UpscaleV1Input struct for UpscaleV1Input
type UpscaleV1Input struct {
	ImageId string `json:"imageId"`
}

type _UpscaleV1Input UpscaleV1Input

// NewUpscaleV1Input instantiates a new UpscaleV1Input object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpscaleV1Input(imageId string) *UpscaleV1Input {
	this := UpscaleV1Input{}
	this.ImageId = imageId
	return &this
}

// NewUpscaleV1InputWithDefaults instantiates a new UpscaleV1Input object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpscaleV1InputWithDefaults() *UpscaleV1Input {
	this := UpscaleV1Input{}
	return &this
}

// GetImageId returns the ImageId field value
func (o *UpscaleV1Input) GetImageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value
// and a boolean to check if the value has been set.
func (o *UpscaleV1Input) GetImageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageId, true
}

// SetImageId sets field value
func (o *UpscaleV1Input) SetImageId(v string) {
	o.ImageId = v
}

func (o UpscaleV1Input) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpscaleV1Input) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["imageId"] = o.ImageId
	return toSerialize, nil
}

func (o *UpscaleV1Input) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"imageId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpscaleV1Input := _UpscaleV1Input{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpscaleV1Input)

	if err != nil {
		return err
	}

	*o = UpscaleV1Input(varUpscaleV1Input)

	return err
}

type NullableUpscaleV1Input struct {
	value *UpscaleV1Input
	isSet bool
}

func (v NullableUpscaleV1Input) Get() *UpscaleV1Input {
	return v.value
}

func (v *NullableUpscaleV1Input) Set(val *UpscaleV1Input) {
	v.value = val
	v.isSet = true
}

func (v NullableUpscaleV1Input) IsSet() bool {
	return v.isSet
}

func (v *NullableUpscaleV1Input) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpscaleV1Input(val *UpscaleV1Input) *NullableUpscaleV1Input {
	return &NullableUpscaleV1Input{value: val, isSet: true}
}

func (v NullableUpscaleV1Input) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpscaleV1Input) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


