/*
Hautech API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hautechapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateMetadataDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateMetadataDto{}

// UpdateMetadataDto struct for UpdateMetadataDto
type UpdateMetadataDto struct {
	Overwrite map[string]interface{} `json:"overwrite"`
}

type _UpdateMetadataDto UpdateMetadataDto

// NewUpdateMetadataDto instantiates a new UpdateMetadataDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateMetadataDto(overwrite map[string]interface{}) *UpdateMetadataDto {
	this := UpdateMetadataDto{}
	this.Overwrite = overwrite
	return &this
}

// NewUpdateMetadataDtoWithDefaults instantiates a new UpdateMetadataDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateMetadataDtoWithDefaults() *UpdateMetadataDto {
	this := UpdateMetadataDto{}
	return &this
}

// GetOverwrite returns the Overwrite field value
func (o *UpdateMetadataDto) GetOverwrite() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Overwrite
}

// GetOverwriteOk returns a tuple with the Overwrite field value
// and a boolean to check if the value has been set.
func (o *UpdateMetadataDto) GetOverwriteOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Overwrite, true
}

// SetOverwrite sets field value
func (o *UpdateMetadataDto) SetOverwrite(v map[string]interface{}) {
	o.Overwrite = v
}

func (o UpdateMetadataDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateMetadataDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["overwrite"] = o.Overwrite
	return toSerialize, nil
}

func (o *UpdateMetadataDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"overwrite",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateMetadataDto := _UpdateMetadataDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateMetadataDto)

	if err != nil {
		return err
	}

	*o = UpdateMetadataDto(varUpdateMetadataDto)

	return err
}

type NullableUpdateMetadataDto struct {
	value *UpdateMetadataDto
	isSet bool
}

func (v NullableUpdateMetadataDto) Get() *UpdateMetadataDto {
	return v.value
}

func (v *NullableUpdateMetadataDto) Set(val *UpdateMetadataDto) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateMetadataDto) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateMetadataDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateMetadataDto(val *UpdateMetadataDto) *NullableUpdateMetadataDto {
	return &NullableUpdateMetadataDto{value: val, isSet: true}
}

func (v NullableUpdateMetadataDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateMetadataDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


