/*
Hautech API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hautechapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetOperationsParamsDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOperationsParamsDto{}

// GetOperationsParamsDto struct for GetOperationsParamsDto
type GetOperationsParamsDto struct {
	Ids []string `json:"ids"`
}

type _GetOperationsParamsDto GetOperationsParamsDto

// NewGetOperationsParamsDto instantiates a new GetOperationsParamsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOperationsParamsDto(ids []string) *GetOperationsParamsDto {
	this := GetOperationsParamsDto{}
	this.Ids = ids
	return &this
}

// NewGetOperationsParamsDtoWithDefaults instantiates a new GetOperationsParamsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOperationsParamsDtoWithDefaults() *GetOperationsParamsDto {
	this := GetOperationsParamsDto{}
	return &this
}

// GetIds returns the Ids field value
func (o *GetOperationsParamsDto) GetIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value
// and a boolean to check if the value has been set.
func (o *GetOperationsParamsDto) GetIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ids, true
}

// SetIds sets field value
func (o *GetOperationsParamsDto) SetIds(v []string) {
	o.Ids = v
}

func (o GetOperationsParamsDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOperationsParamsDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ids"] = o.Ids
	return toSerialize, nil
}

func (o *GetOperationsParamsDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetOperationsParamsDto := _GetOperationsParamsDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetOperationsParamsDto)

	if err != nil {
		return err
	}

	*o = GetOperationsParamsDto(varGetOperationsParamsDto)

	return err
}

type NullableGetOperationsParamsDto struct {
	value *GetOperationsParamsDto
	isSet bool
}

func (v NullableGetOperationsParamsDto) Get() *GetOperationsParamsDto {
	return v.value
}

func (v *NullableGetOperationsParamsDto) Set(val *GetOperationsParamsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOperationsParamsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOperationsParamsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOperationsParamsDto(val *GetOperationsParamsDto) *NullableGetOperationsParamsDto {
	return &NullableGetOperationsParamsDto{value: val, isSet: true}
}

func (v NullableGetOperationsParamsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOperationsParamsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


