/*
Hautech API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hautechapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListOperationsDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListOperationsDto{}

// ListOperationsDto struct for ListOperationsDto
type ListOperationsDto struct {
	Data []OperationEntity `json:"data"`
	PageInfo ListAccountsDtoPageInfo `json:"pageInfo"`
}

type _ListOperationsDto ListOperationsDto

// NewListOperationsDto instantiates a new ListOperationsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListOperationsDto(data []OperationEntity, pageInfo ListAccountsDtoPageInfo) *ListOperationsDto {
	this := ListOperationsDto{}
	this.Data = data
	this.PageInfo = pageInfo
	return &this
}

// NewListOperationsDtoWithDefaults instantiates a new ListOperationsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListOperationsDtoWithDefaults() *ListOperationsDto {
	this := ListOperationsDto{}
	return &this
}

// GetData returns the Data field value
func (o *ListOperationsDto) GetData() []OperationEntity {
	if o == nil {
		var ret []OperationEntity
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListOperationsDto) GetDataOk() ([]OperationEntity, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListOperationsDto) SetData(v []OperationEntity) {
	o.Data = v
}

// GetPageInfo returns the PageInfo field value
func (o *ListOperationsDto) GetPageInfo() ListAccountsDtoPageInfo {
	if o == nil {
		var ret ListAccountsDtoPageInfo
		return ret
	}

	return o.PageInfo
}

// GetPageInfoOk returns a tuple with the PageInfo field value
// and a boolean to check if the value has been set.
func (o *ListOperationsDto) GetPageInfoOk() (*ListAccountsDtoPageInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageInfo, true
}

// SetPageInfo sets field value
func (o *ListOperationsDto) SetPageInfo(v ListAccountsDtoPageInfo) {
	o.PageInfo = v
}

func (o ListOperationsDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListOperationsDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["pageInfo"] = o.PageInfo
	return toSerialize, nil
}

func (o *ListOperationsDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"pageInfo",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListOperationsDto := _ListOperationsDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListOperationsDto)

	if err != nil {
		return err
	}

	*o = ListOperationsDto(varListOperationsDto)

	return err
}

type NullableListOperationsDto struct {
	value *ListOperationsDto
	isSet bool
}

func (v NullableListOperationsDto) Get() *ListOperationsDto {
	return v.value
}

func (v *NullableListOperationsDto) Set(val *ListOperationsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableListOperationsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableListOperationsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListOperationsDto(val *ListOperationsDto) *NullableListOperationsDto {
	return &NullableListOperationsDto{value: val, isSet: true}
}

func (v NullableListOperationsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListOperationsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


