/*
Hautech API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hautechapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListAccountsDtoPageInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAccountsDtoPageInfo{}

// ListAccountsDtoPageInfo struct for ListAccountsDtoPageInfo
type ListAccountsDtoPageInfo struct {
	NextCursor string `json:"nextCursor"`
}

type _ListAccountsDtoPageInfo ListAccountsDtoPageInfo

// NewListAccountsDtoPageInfo instantiates a new ListAccountsDtoPageInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAccountsDtoPageInfo(nextCursor string) *ListAccountsDtoPageInfo {
	this := ListAccountsDtoPageInfo{}
	this.NextCursor = nextCursor
	return &this
}

// NewListAccountsDtoPageInfoWithDefaults instantiates a new ListAccountsDtoPageInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAccountsDtoPageInfoWithDefaults() *ListAccountsDtoPageInfo {
	this := ListAccountsDtoPageInfo{}
	return &this
}

// GetNextCursor returns the NextCursor field value
func (o *ListAccountsDtoPageInfo) GetNextCursor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value
// and a boolean to check if the value has been set.
func (o *ListAccountsDtoPageInfo) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextCursor, true
}

// SetNextCursor sets field value
func (o *ListAccountsDtoPageInfo) SetNextCursor(v string) {
	o.NextCursor = v
}

func (o ListAccountsDtoPageInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAccountsDtoPageInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nextCursor"] = o.NextCursor
	return toSerialize, nil
}

func (o *ListAccountsDtoPageInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"nextCursor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListAccountsDtoPageInfo := _ListAccountsDtoPageInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListAccountsDtoPageInfo)

	if err != nil {
		return err
	}

	*o = ListAccountsDtoPageInfo(varListAccountsDtoPageInfo)

	return err
}

type NullableListAccountsDtoPageInfo struct {
	value *ListAccountsDtoPageInfo
	isSet bool
}

func (v NullableListAccountsDtoPageInfo) Get() *ListAccountsDtoPageInfo {
	return v.value
}

func (v *NullableListAccountsDtoPageInfo) Set(val *ListAccountsDtoPageInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableListAccountsDtoPageInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableListAccountsDtoPageInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAccountsDtoPageInfo(val *ListAccountsDtoPageInfo) *NullableListAccountsDtoPageInfo {
	return &NullableListAccountsDtoPageInfo{value: val, isSet: true}
}

func (v NullableListAccountsDtoPageInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAccountsDtoPageInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


