/*
Hautech API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hautechapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListAccessControllerGrantsDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAccessControllerGrantsDto{}

// ListAccessControllerGrantsDto struct for ListAccessControllerGrantsDto
type ListAccessControllerGrantsDto struct {
	PrincipalId string `json:"principalId"`
	PrincipalType string `json:"principalType"`
	Access string `json:"access"`
}

type _ListAccessControllerGrantsDto ListAccessControllerGrantsDto

// NewListAccessControllerGrantsDto instantiates a new ListAccessControllerGrantsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAccessControllerGrantsDto(principalId string, principalType string, access string) *ListAccessControllerGrantsDto {
	this := ListAccessControllerGrantsDto{}
	this.PrincipalId = principalId
	this.PrincipalType = principalType
	this.Access = access
	return &this
}

// NewListAccessControllerGrantsDtoWithDefaults instantiates a new ListAccessControllerGrantsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAccessControllerGrantsDtoWithDefaults() *ListAccessControllerGrantsDto {
	this := ListAccessControllerGrantsDto{}
	return &this
}

// GetPrincipalId returns the PrincipalId field value
func (o *ListAccessControllerGrantsDto) GetPrincipalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrincipalId
}

// GetPrincipalIdOk returns a tuple with the PrincipalId field value
// and a boolean to check if the value has been set.
func (o *ListAccessControllerGrantsDto) GetPrincipalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrincipalId, true
}

// SetPrincipalId sets field value
func (o *ListAccessControllerGrantsDto) SetPrincipalId(v string) {
	o.PrincipalId = v
}

// GetPrincipalType returns the PrincipalType field value
func (o *ListAccessControllerGrantsDto) GetPrincipalType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrincipalType
}

// GetPrincipalTypeOk returns a tuple with the PrincipalType field value
// and a boolean to check if the value has been set.
func (o *ListAccessControllerGrantsDto) GetPrincipalTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrincipalType, true
}

// SetPrincipalType sets field value
func (o *ListAccessControllerGrantsDto) SetPrincipalType(v string) {
	o.PrincipalType = v
}

// GetAccess returns the Access field value
func (o *ListAccessControllerGrantsDto) GetAccess() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Access
}

// GetAccessOk returns a tuple with the Access field value
// and a boolean to check if the value has been set.
func (o *ListAccessControllerGrantsDto) GetAccessOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Access, true
}

// SetAccess sets field value
func (o *ListAccessControllerGrantsDto) SetAccess(v string) {
	o.Access = v
}

func (o ListAccessControllerGrantsDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAccessControllerGrantsDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["principalId"] = o.PrincipalId
	toSerialize["principalType"] = o.PrincipalType
	toSerialize["access"] = o.Access
	return toSerialize, nil
}

func (o *ListAccessControllerGrantsDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"principalId",
		"principalType",
		"access",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListAccessControllerGrantsDto := _ListAccessControllerGrantsDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListAccessControllerGrantsDto)

	if err != nil {
		return err
	}

	*o = ListAccessControllerGrantsDto(varListAccessControllerGrantsDto)

	return err
}

type NullableListAccessControllerGrantsDto struct {
	value *ListAccessControllerGrantsDto
	isSet bool
}

func (v NullableListAccessControllerGrantsDto) Get() *ListAccessControllerGrantsDto {
	return v.value
}

func (v *NullableListAccessControllerGrantsDto) Set(val *ListAccessControllerGrantsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableListAccessControllerGrantsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableListAccessControllerGrantsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAccessControllerGrantsDto(val *ListAccessControllerGrantsDto) *NullableListAccessControllerGrantsDto {
	return &NullableListAccessControllerGrantsDto{value: val, isSet: true}
}

func (v NullableListAccessControllerGrantsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAccessControllerGrantsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


