/*
Hautech API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hautechapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddBalanceParamsDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddBalanceParamsDto{}

// AddBalanceParamsDto struct for AddBalanceParamsDto
type AddBalanceParamsDto struct {
	Amount string `json:"amount"`
	AccountId string `json:"accountId"`
}

type _AddBalanceParamsDto AddBalanceParamsDto

// NewAddBalanceParamsDto instantiates a new AddBalanceParamsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddBalanceParamsDto(amount string, accountId string) *AddBalanceParamsDto {
	this := AddBalanceParamsDto{}
	this.Amount = amount
	this.AccountId = accountId
	return &this
}

// NewAddBalanceParamsDtoWithDefaults instantiates a new AddBalanceParamsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddBalanceParamsDtoWithDefaults() *AddBalanceParamsDto {
	this := AddBalanceParamsDto{}
	return &this
}

// GetAmount returns the Amount field value
func (o *AddBalanceParamsDto) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *AddBalanceParamsDto) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *AddBalanceParamsDto) SetAmount(v string) {
	o.Amount = v
}

// GetAccountId returns the AccountId field value
func (o *AddBalanceParamsDto) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *AddBalanceParamsDto) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *AddBalanceParamsDto) SetAccountId(v string) {
	o.AccountId = v
}

func (o AddBalanceParamsDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddBalanceParamsDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amount"] = o.Amount
	toSerialize["accountId"] = o.AccountId
	return toSerialize, nil
}

func (o *AddBalanceParamsDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amount",
		"accountId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddBalanceParamsDto := _AddBalanceParamsDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddBalanceParamsDto)

	if err != nil {
		return err
	}

	*o = AddBalanceParamsDto(varAddBalanceParamsDto)

	return err
}

type NullableAddBalanceParamsDto struct {
	value *AddBalanceParamsDto
	isSet bool
}

func (v NullableAddBalanceParamsDto) Get() *AddBalanceParamsDto {
	return v.value
}

func (v *NullableAddBalanceParamsDto) Set(val *AddBalanceParamsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableAddBalanceParamsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableAddBalanceParamsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddBalanceParamsDto(val *AddBalanceParamsDto) *NullableAddBalanceParamsDto {
	return &NullableAddBalanceParamsDto{value: val, isSet: true}
}

func (v NullableAddBalanceParamsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddBalanceParamsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


