/*
Hautech API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hautechapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteParamsDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteParamsDto{}

// DeleteParamsDto struct for DeleteParamsDto
type DeleteParamsDto struct {
	Id string `json:"id"`
}

type _DeleteParamsDto DeleteParamsDto

// NewDeleteParamsDto instantiates a new DeleteParamsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteParamsDto(id string) *DeleteParamsDto {
	this := DeleteParamsDto{}
	this.Id = id
	return &this
}

// NewDeleteParamsDtoWithDefaults instantiates a new DeleteParamsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteParamsDtoWithDefaults() *DeleteParamsDto {
	this := DeleteParamsDto{}
	return &this
}

// GetId returns the Id field value
func (o *DeleteParamsDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeleteParamsDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeleteParamsDto) SetId(v string) {
	o.Id = v
}

func (o DeleteParamsDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteParamsDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *DeleteParamsDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteParamsDto := _DeleteParamsDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteParamsDto)

	if err != nil {
		return err
	}

	*o = DeleteParamsDto(varDeleteParamsDto)

	return err
}

type NullableDeleteParamsDto struct {
	value *DeleteParamsDto
	isSet bool
}

func (v NullableDeleteParamsDto) Get() *DeleteParamsDto {
	return v.value
}

func (v *NullableDeleteParamsDto) Set(val *DeleteParamsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteParamsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteParamsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteParamsDto(val *DeleteParamsDto) *NullableDeleteParamsDto {
	return &NullableDeleteParamsDto{value: val, isSet: true}
}

func (v NullableDeleteParamsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteParamsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


