/*
Hautech API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hautechapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetImageRepresentationParamsDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetImageRepresentationParamsDto{}

// GetImageRepresentationParamsDto struct for GetImageRepresentationParamsDto
type GetImageRepresentationParamsDto struct {
	ImageId string `json:"imageId"`
	Type string `json:"type"`
}

type _GetImageRepresentationParamsDto GetImageRepresentationParamsDto

// NewGetImageRepresentationParamsDto instantiates a new GetImageRepresentationParamsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetImageRepresentationParamsDto(imageId string, type_ string) *GetImageRepresentationParamsDto {
	this := GetImageRepresentationParamsDto{}
	this.ImageId = imageId
	this.Type = type_
	return &this
}

// NewGetImageRepresentationParamsDtoWithDefaults instantiates a new GetImageRepresentationParamsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetImageRepresentationParamsDtoWithDefaults() *GetImageRepresentationParamsDto {
	this := GetImageRepresentationParamsDto{}
	return &this
}

// GetImageId returns the ImageId field value
func (o *GetImageRepresentationParamsDto) GetImageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value
// and a boolean to check if the value has been set.
func (o *GetImageRepresentationParamsDto) GetImageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageId, true
}

// SetImageId sets field value
func (o *GetImageRepresentationParamsDto) SetImageId(v string) {
	o.ImageId = v
}

// GetType returns the Type field value
func (o *GetImageRepresentationParamsDto) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GetImageRepresentationParamsDto) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GetImageRepresentationParamsDto) SetType(v string) {
	o.Type = v
}

func (o GetImageRepresentationParamsDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetImageRepresentationParamsDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["imageId"] = o.ImageId
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *GetImageRepresentationParamsDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"imageId",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetImageRepresentationParamsDto := _GetImageRepresentationParamsDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetImageRepresentationParamsDto)

	if err != nil {
		return err
	}

	*o = GetImageRepresentationParamsDto(varGetImageRepresentationParamsDto)

	return err
}

type NullableGetImageRepresentationParamsDto struct {
	value *GetImageRepresentationParamsDto
	isSet bool
}

func (v NullableGetImageRepresentationParamsDto) Get() *GetImageRepresentationParamsDto {
	return v.value
}

func (v *NullableGetImageRepresentationParamsDto) Set(val *GetImageRepresentationParamsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableGetImageRepresentationParamsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableGetImageRepresentationParamsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetImageRepresentationParamsDto(val *GetImageRepresentationParamsDto) *NullableGetImageRepresentationParamsDto {
	return &NullableGetImageRepresentationParamsDto{value: val, isSet: true}
}

func (v NullableGetImageRepresentationParamsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetImageRepresentationParamsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


