/*
Hautech API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hautechapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GrantAccessControllerParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GrantAccessControllerParams{}

// GrantAccessControllerParams struct for GrantAccessControllerParams
type GrantAccessControllerParams struct {
	PrincipalType string `json:"principalType"`
	PrincipalId string `json:"principalId"`
	Access string `json:"access"`
}

type _GrantAccessControllerParams GrantAccessControllerParams

// NewGrantAccessControllerParams instantiates a new GrantAccessControllerParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGrantAccessControllerParams(principalType string, principalId string, access string) *GrantAccessControllerParams {
	this := GrantAccessControllerParams{}
	this.PrincipalType = principalType
	this.PrincipalId = principalId
	this.Access = access
	return &this
}

// NewGrantAccessControllerParamsWithDefaults instantiates a new GrantAccessControllerParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGrantAccessControllerParamsWithDefaults() *GrantAccessControllerParams {
	this := GrantAccessControllerParams{}
	return &this
}

// GetPrincipalType returns the PrincipalType field value
func (o *GrantAccessControllerParams) GetPrincipalType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrincipalType
}

// GetPrincipalTypeOk returns a tuple with the PrincipalType field value
// and a boolean to check if the value has been set.
func (o *GrantAccessControllerParams) GetPrincipalTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrincipalType, true
}

// SetPrincipalType sets field value
func (o *GrantAccessControllerParams) SetPrincipalType(v string) {
	o.PrincipalType = v
}

// GetPrincipalId returns the PrincipalId field value
func (o *GrantAccessControllerParams) GetPrincipalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrincipalId
}

// GetPrincipalIdOk returns a tuple with the PrincipalId field value
// and a boolean to check if the value has been set.
func (o *GrantAccessControllerParams) GetPrincipalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrincipalId, true
}

// SetPrincipalId sets field value
func (o *GrantAccessControllerParams) SetPrincipalId(v string) {
	o.PrincipalId = v
}

// GetAccess returns the Access field value
func (o *GrantAccessControllerParams) GetAccess() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Access
}

// GetAccessOk returns a tuple with the Access field value
// and a boolean to check if the value has been set.
func (o *GrantAccessControllerParams) GetAccessOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Access, true
}

// SetAccess sets field value
func (o *GrantAccessControllerParams) SetAccess(v string) {
	o.Access = v
}

func (o GrantAccessControllerParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GrantAccessControllerParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["principalType"] = o.PrincipalType
	toSerialize["principalId"] = o.PrincipalId
	toSerialize["access"] = o.Access
	return toSerialize, nil
}

func (o *GrantAccessControllerParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"principalType",
		"principalId",
		"access",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGrantAccessControllerParams := _GrantAccessControllerParams{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGrantAccessControllerParams)

	if err != nil {
		return err
	}

	*o = GrantAccessControllerParams(varGrantAccessControllerParams)

	return err
}

type NullableGrantAccessControllerParams struct {
	value *GrantAccessControllerParams
	isSet bool
}

func (v NullableGrantAccessControllerParams) Get() *GrantAccessControllerParams {
	return v.value
}

func (v *NullableGrantAccessControllerParams) Set(val *GrantAccessControllerParams) {
	v.value = val
	v.isSet = true
}

func (v NullableGrantAccessControllerParams) IsSet() bool {
	return v.isSet
}

func (v *NullableGrantAccessControllerParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGrantAccessControllerParams(val *GrantAccessControllerParams) *NullableGrantAccessControllerParams {
	return &NullableGrantAccessControllerParams{value: val, isSet: true}
}

func (v NullableGrantAccessControllerParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGrantAccessControllerParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


