/*
Hautech API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hautechapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateResourceMetadataDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateResourceMetadataDto{}

// UpdateResourceMetadataDto struct for UpdateResourceMetadataDto
type UpdateResourceMetadataDto struct {
	Id string `json:"id"`
	Update UpdateMetadataDto `json:"update"`
}

type _UpdateResourceMetadataDto UpdateResourceMetadataDto

// NewUpdateResourceMetadataDto instantiates a new UpdateResourceMetadataDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateResourceMetadataDto(id string, update UpdateMetadataDto) *UpdateResourceMetadataDto {
	this := UpdateResourceMetadataDto{}
	this.Id = id
	this.Update = update
	return &this
}

// NewUpdateResourceMetadataDtoWithDefaults instantiates a new UpdateResourceMetadataDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateResourceMetadataDtoWithDefaults() *UpdateResourceMetadataDto {
	this := UpdateResourceMetadataDto{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateResourceMetadataDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateResourceMetadataDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateResourceMetadataDto) SetId(v string) {
	o.Id = v
}

// GetUpdate returns the Update field value
func (o *UpdateResourceMetadataDto) GetUpdate() UpdateMetadataDto {
	if o == nil {
		var ret UpdateMetadataDto
		return ret
	}

	return o.Update
}

// GetUpdateOk returns a tuple with the Update field value
// and a boolean to check if the value has been set.
func (o *UpdateResourceMetadataDto) GetUpdateOk() (*UpdateMetadataDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Update, true
}

// SetUpdate sets field value
func (o *UpdateResourceMetadataDto) SetUpdate(v UpdateMetadataDto) {
	o.Update = v
}

func (o UpdateResourceMetadataDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateResourceMetadataDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["update"] = o.Update
	return toSerialize, nil
}

func (o *UpdateResourceMetadataDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"update",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateResourceMetadataDto := _UpdateResourceMetadataDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateResourceMetadataDto)

	if err != nil {
		return err
	}

	*o = UpdateResourceMetadataDto(varUpdateResourceMetadataDto)

	return err
}

type NullableUpdateResourceMetadataDto struct {
	value *UpdateResourceMetadataDto
	isSet bool
}

func (v NullableUpdateResourceMetadataDto) Get() *UpdateResourceMetadataDto {
	return v.value
}

func (v *NullableUpdateResourceMetadataDto) Set(val *UpdateResourceMetadataDto) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateResourceMetadataDto) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateResourceMetadataDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateResourceMetadataDto(val *UpdateResourceMetadataDto) *NullableUpdateResourceMetadataDto {
	return &NullableUpdateResourceMetadataDto{value: val, isSet: true}
}

func (v NullableUpdateResourceMetadataDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateResourceMetadataDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


