/*
Hautech API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hautechapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OperationOutputImageSingle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperationOutputImageSingle{}

// OperationOutputImageSingle struct for OperationOutputImageSingle
type OperationOutputImageSingle struct {
	Kind string `json:"kind"`
	ImageId string `json:"imageId"`
}

type _OperationOutputImageSingle OperationOutputImageSingle

// NewOperationOutputImageSingle instantiates a new OperationOutputImageSingle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperationOutputImageSingle(kind string, imageId string) *OperationOutputImageSingle {
	this := OperationOutputImageSingle{}
	this.Kind = kind
	this.ImageId = imageId
	return &this
}

// NewOperationOutputImageSingleWithDefaults instantiates a new OperationOutputImageSingle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperationOutputImageSingleWithDefaults() *OperationOutputImageSingle {
	this := OperationOutputImageSingle{}
	return &this
}

// GetKind returns the Kind field value
func (o *OperationOutputImageSingle) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *OperationOutputImageSingle) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *OperationOutputImageSingle) SetKind(v string) {
	o.Kind = v
}

// GetImageId returns the ImageId field value
func (o *OperationOutputImageSingle) GetImageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value
// and a boolean to check if the value has been set.
func (o *OperationOutputImageSingle) GetImageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageId, true
}

// SetImageId sets field value
func (o *OperationOutputImageSingle) SetImageId(v string) {
	o.ImageId = v
}

func (o OperationOutputImageSingle) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperationOutputImageSingle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	toSerialize["imageId"] = o.ImageId
	return toSerialize, nil
}

func (o *OperationOutputImageSingle) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
		"imageId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOperationOutputImageSingle := _OperationOutputImageSingle{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOperationOutputImageSingle)

	if err != nil {
		return err
	}

	*o = OperationOutputImageSingle(varOperationOutputImageSingle)

	return err
}

type NullableOperationOutputImageSingle struct {
	value *OperationOutputImageSingle
	isSet bool
}

func (v NullableOperationOutputImageSingle) Get() *OperationOutputImageSingle {
	return v.value
}

func (v *NullableOperationOutputImageSingle) Set(val *OperationOutputImageSingle) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationOutputImageSingle) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationOutputImageSingle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationOutputImageSingle(val *OperationOutputImageSingle) *NullableOperationOutputImageSingle {
	return &NullableOperationOutputImageSingle{value: val, isSet: true}
}

func (v NullableOperationOutputImageSingle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationOutputImageSingle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


