/*
Hautech API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hautechapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ObjectDetectionV1Input type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObjectDetectionV1Input{}

// ObjectDetectionV1Input struct for ObjectDetectionV1Input
type ObjectDetectionV1Input struct {
	Labels []string `json:"labels"`
	ImageId string `json:"imageId"`
}

type _ObjectDetectionV1Input ObjectDetectionV1Input

// NewObjectDetectionV1Input instantiates a new ObjectDetectionV1Input object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObjectDetectionV1Input(labels []string, imageId string) *ObjectDetectionV1Input {
	this := ObjectDetectionV1Input{}
	this.Labels = labels
	this.ImageId = imageId
	return &this
}

// NewObjectDetectionV1InputWithDefaults instantiates a new ObjectDetectionV1Input object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObjectDetectionV1InputWithDefaults() *ObjectDetectionV1Input {
	this := ObjectDetectionV1Input{}
	return &this
}

// GetLabels returns the Labels field value
func (o *ObjectDetectionV1Input) GetLabels() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value
// and a boolean to check if the value has been set.
func (o *ObjectDetectionV1Input) GetLabelsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Labels, true
}

// SetLabels sets field value
func (o *ObjectDetectionV1Input) SetLabels(v []string) {
	o.Labels = v
}

// GetImageId returns the ImageId field value
func (o *ObjectDetectionV1Input) GetImageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value
// and a boolean to check if the value has been set.
func (o *ObjectDetectionV1Input) GetImageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageId, true
}

// SetImageId sets field value
func (o *ObjectDetectionV1Input) SetImageId(v string) {
	o.ImageId = v
}

func (o ObjectDetectionV1Input) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObjectDetectionV1Input) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["labels"] = o.Labels
	toSerialize["imageId"] = o.ImageId
	return toSerialize, nil
}

func (o *ObjectDetectionV1Input) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"labels",
		"imageId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varObjectDetectionV1Input := _ObjectDetectionV1Input{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varObjectDetectionV1Input)

	if err != nil {
		return err
	}

	*o = ObjectDetectionV1Input(varObjectDetectionV1Input)

	return err
}

type NullableObjectDetectionV1Input struct {
	value *ObjectDetectionV1Input
	isSet bool
}

func (v NullableObjectDetectionV1Input) Get() *ObjectDetectionV1Input {
	return v.value
}

func (v *NullableObjectDetectionV1Input) Set(val *ObjectDetectionV1Input) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectDetectionV1Input) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectDetectionV1Input) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectDetectionV1Input(val *ObjectDetectionV1Input) *NullableObjectDetectionV1Input {
	return &NullableObjectDetectionV1Input{value: val, isSet: true}
}

func (v NullableObjectDetectionV1Input) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectDetectionV1Input) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


