/*
Hautech API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hautechapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CropV1Input type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CropV1Input{}

// CropV1Input struct for CropV1Input
type CropV1Input struct {
	ImageId string `json:"imageId"`
	Left float32 `json:"left"`
	Top float32 `json:"top"`
	Width float32 `json:"width"`
	Height float32 `json:"height"`
}

type _CropV1Input CropV1Input

// NewCropV1Input instantiates a new CropV1Input object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCropV1Input(imageId string, left float32, top float32, width float32, height float32) *CropV1Input {
	this := CropV1Input{}
	this.ImageId = imageId
	this.Left = left
	this.Top = top
	this.Width = width
	this.Height = height
	return &this
}

// NewCropV1InputWithDefaults instantiates a new CropV1Input object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCropV1InputWithDefaults() *CropV1Input {
	this := CropV1Input{}
	return &this
}

// GetImageId returns the ImageId field value
func (o *CropV1Input) GetImageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value
// and a boolean to check if the value has been set.
func (o *CropV1Input) GetImageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageId, true
}

// SetImageId sets field value
func (o *CropV1Input) SetImageId(v string) {
	o.ImageId = v
}

// GetLeft returns the Left field value
func (o *CropV1Input) GetLeft() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Left
}

// GetLeftOk returns a tuple with the Left field value
// and a boolean to check if the value has been set.
func (o *CropV1Input) GetLeftOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Left, true
}

// SetLeft sets field value
func (o *CropV1Input) SetLeft(v float32) {
	o.Left = v
}

// GetTop returns the Top field value
func (o *CropV1Input) GetTop() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Top
}

// GetTopOk returns a tuple with the Top field value
// and a boolean to check if the value has been set.
func (o *CropV1Input) GetTopOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Top, true
}

// SetTop sets field value
func (o *CropV1Input) SetTop(v float32) {
	o.Top = v
}

// GetWidth returns the Width field value
func (o *CropV1Input) GetWidth() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Width
}

// GetWidthOk returns a tuple with the Width field value
// and a boolean to check if the value has been set.
func (o *CropV1Input) GetWidthOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Width, true
}

// SetWidth sets field value
func (o *CropV1Input) SetWidth(v float32) {
	o.Width = v
}

// GetHeight returns the Height field value
func (o *CropV1Input) GetHeight() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Height
}

// GetHeightOk returns a tuple with the Height field value
// and a boolean to check if the value has been set.
func (o *CropV1Input) GetHeightOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Height, true
}

// SetHeight sets field value
func (o *CropV1Input) SetHeight(v float32) {
	o.Height = v
}

func (o CropV1Input) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CropV1Input) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["imageId"] = o.ImageId
	toSerialize["left"] = o.Left
	toSerialize["top"] = o.Top
	toSerialize["width"] = o.Width
	toSerialize["height"] = o.Height
	return toSerialize, nil
}

func (o *CropV1Input) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"imageId",
		"left",
		"top",
		"width",
		"height",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCropV1Input := _CropV1Input{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCropV1Input)

	if err != nil {
		return err
	}

	*o = CropV1Input(varCropV1Input)

	return err
}

type NullableCropV1Input struct {
	value *CropV1Input
	isSet bool
}

func (v NullableCropV1Input) Get() *CropV1Input {
	return v.value
}

func (v *NullableCropV1Input) Set(val *CropV1Input) {
	v.value = val
	v.isSet = true
}

func (v NullableCropV1Input) IsSet() bool {
	return v.isSet
}

func (v *NullableCropV1Input) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCropV1Input(val *CropV1Input) *NullableCropV1Input {
	return &NullableCropV1Input{value: val, isSet: true}
}

func (v NullableCropV1Input) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCropV1Input) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


