/*
Hautech API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hautechapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SegmentAnythingMaskV1Request type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SegmentAnythingMaskV1Request{}

// SegmentAnythingMaskV1Request struct for SegmentAnythingMaskV1Request
type SegmentAnythingMaskV1Request struct {
	Input SegmentAnythingMaskV1Input `json:"input"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

type _SegmentAnythingMaskV1Request SegmentAnythingMaskV1Request

// NewSegmentAnythingMaskV1Request instantiates a new SegmentAnythingMaskV1Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSegmentAnythingMaskV1Request(input SegmentAnythingMaskV1Input) *SegmentAnythingMaskV1Request {
	this := SegmentAnythingMaskV1Request{}
	this.Input = input
	return &this
}

// NewSegmentAnythingMaskV1RequestWithDefaults instantiates a new SegmentAnythingMaskV1Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSegmentAnythingMaskV1RequestWithDefaults() *SegmentAnythingMaskV1Request {
	this := SegmentAnythingMaskV1Request{}
	return &this
}

// GetInput returns the Input field value
func (o *SegmentAnythingMaskV1Request) GetInput() SegmentAnythingMaskV1Input {
	if o == nil {
		var ret SegmentAnythingMaskV1Input
		return ret
	}

	return o.Input
}

// GetInputOk returns a tuple with the Input field value
// and a boolean to check if the value has been set.
func (o *SegmentAnythingMaskV1Request) GetInputOk() (*SegmentAnythingMaskV1Input, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Input, true
}

// SetInput sets field value
func (o *SegmentAnythingMaskV1Request) SetInput(v SegmentAnythingMaskV1Input) {
	o.Input = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *SegmentAnythingMaskV1Request) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SegmentAnythingMaskV1Request) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *SegmentAnythingMaskV1Request) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *SegmentAnythingMaskV1Request) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o SegmentAnythingMaskV1Request) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SegmentAnythingMaskV1Request) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["input"] = o.Input
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *SegmentAnythingMaskV1Request) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"input",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSegmentAnythingMaskV1Request := _SegmentAnythingMaskV1Request{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSegmentAnythingMaskV1Request)

	if err != nil {
		return err
	}

	*o = SegmentAnythingMaskV1Request(varSegmentAnythingMaskV1Request)

	return err
}

type NullableSegmentAnythingMaskV1Request struct {
	value *SegmentAnythingMaskV1Request
	isSet bool
}

func (v NullableSegmentAnythingMaskV1Request) Get() *SegmentAnythingMaskV1Request {
	return v.value
}

func (v *NullableSegmentAnythingMaskV1Request) Set(val *SegmentAnythingMaskV1Request) {
	v.value = val
	v.isSet = true
}

func (v NullableSegmentAnythingMaskV1Request) IsSet() bool {
	return v.isSet
}

func (v *NullableSegmentAnythingMaskV1Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSegmentAnythingMaskV1Request(val *SegmentAnythingMaskV1Request) *NullableSegmentAnythingMaskV1Request {
	return &NullableSegmentAnythingMaskV1Request{value: val, isSet: true}
}

func (v NullableSegmentAnythingMaskV1Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSegmentAnythingMaskV1Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


