/*
Hautech API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hautechapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateStorageRecordParamsDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateStorageRecordParamsDto{}

// UpdateStorageRecordParamsDto struct for UpdateStorageRecordParamsDto
type UpdateStorageRecordParamsDto struct {
	Key string `json:"key"`
	Value map[string]interface{} `json:"value"`
}

type _UpdateStorageRecordParamsDto UpdateStorageRecordParamsDto

// NewUpdateStorageRecordParamsDto instantiates a new UpdateStorageRecordParamsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateStorageRecordParamsDto(key string, value map[string]interface{}) *UpdateStorageRecordParamsDto {
	this := UpdateStorageRecordParamsDto{}
	this.Key = key
	this.Value = value
	return &this
}

// NewUpdateStorageRecordParamsDtoWithDefaults instantiates a new UpdateStorageRecordParamsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateStorageRecordParamsDtoWithDefaults() *UpdateStorageRecordParamsDto {
	this := UpdateStorageRecordParamsDto{}
	return &this
}

// GetKey returns the Key field value
func (o *UpdateStorageRecordParamsDto) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *UpdateStorageRecordParamsDto) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *UpdateStorageRecordParamsDto) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value
func (o *UpdateStorageRecordParamsDto) GetValue() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *UpdateStorageRecordParamsDto) GetValueOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Value, true
}

// SetValue sets field value
func (o *UpdateStorageRecordParamsDto) SetValue(v map[string]interface{}) {
	o.Value = v
}

func (o UpdateStorageRecordParamsDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateStorageRecordParamsDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *UpdateStorageRecordParamsDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateStorageRecordParamsDto := _UpdateStorageRecordParamsDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateStorageRecordParamsDto)

	if err != nil {
		return err
	}

	*o = UpdateStorageRecordParamsDto(varUpdateStorageRecordParamsDto)

	return err
}

type NullableUpdateStorageRecordParamsDto struct {
	value *UpdateStorageRecordParamsDto
	isSet bool
}

func (v NullableUpdateStorageRecordParamsDto) Get() *UpdateStorageRecordParamsDto {
	return v.value
}

func (v *NullableUpdateStorageRecordParamsDto) Set(val *UpdateStorageRecordParamsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateStorageRecordParamsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateStorageRecordParamsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateStorageRecordParamsDto(val *UpdateStorageRecordParamsDto) *NullableUpdateStorageRecordParamsDto {
	return &NullableUpdateStorageRecordParamsDto{value: val, isSet: true}
}

func (v NullableUpdateStorageRecordParamsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateStorageRecordParamsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


