/*
Hautech API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hautechapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NaomiHauteV1Input type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NaomiHauteV1Input{}

// NaomiHauteV1Input struct for NaomiHauteV1Input
type NaomiHauteV1Input struct {
	// UNSTABLE
	LoraIds []string `json:"loraIds,omitempty"`
	Prompt string `json:"prompt"`
	Category string `json:"category"`
	GarmentImageId string `json:"garmentImageId"`
	PoseId string `json:"poseId"`
	Seed float32 `json:"seed"`
	Width float32 `json:"width"`
	Height float32 `json:"height"`
	TextGuidanceScale *float32 `json:"textGuidanceScale,omitempty"`
	ImageGuidanceScale *float32 `json:"imageGuidanceScale,omitempty"`
	NumInferenceSteps *float32 `json:"numInferenceSteps,omitempty"`
	Mode *string `json:"mode,omitempty"`
}

type _NaomiHauteV1Input NaomiHauteV1Input

// NewNaomiHauteV1Input instantiates a new NaomiHauteV1Input object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNaomiHauteV1Input(prompt string, category string, garmentImageId string, poseId string, seed float32, width float32, height float32) *NaomiHauteV1Input {
	this := NaomiHauteV1Input{}
	this.Prompt = prompt
	this.Category = category
	this.GarmentImageId = garmentImageId
	this.PoseId = poseId
	this.Seed = seed
	this.Width = width
	this.Height = height
	var textGuidanceScale float32 = 2.5
	this.TextGuidanceScale = &textGuidanceScale
	var imageGuidanceScale float32 = 1.6
	this.ImageGuidanceScale = &imageGuidanceScale
	var numInferenceSteps float32 = 50
	this.NumInferenceSteps = &numInferenceSteps
	var mode string = "apparel_to_model"
	this.Mode = &mode
	return &this
}

// NewNaomiHauteV1InputWithDefaults instantiates a new NaomiHauteV1Input object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNaomiHauteV1InputWithDefaults() *NaomiHauteV1Input {
	this := NaomiHauteV1Input{}
	var textGuidanceScale float32 = 2.5
	this.TextGuidanceScale = &textGuidanceScale
	var imageGuidanceScale float32 = 1.6
	this.ImageGuidanceScale = &imageGuidanceScale
	var numInferenceSteps float32 = 50
	this.NumInferenceSteps = &numInferenceSteps
	var mode string = "apparel_to_model"
	this.Mode = &mode
	return &this
}

// GetLoraIds returns the LoraIds field value if set, zero value otherwise.
func (o *NaomiHauteV1Input) GetLoraIds() []string {
	if o == nil || IsNil(o.LoraIds) {
		var ret []string
		return ret
	}
	return o.LoraIds
}

// GetLoraIdsOk returns a tuple with the LoraIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NaomiHauteV1Input) GetLoraIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.LoraIds) {
		return nil, false
	}
	return o.LoraIds, true
}

// HasLoraIds returns a boolean if a field has been set.
func (o *NaomiHauteV1Input) HasLoraIds() bool {
	if o != nil && !IsNil(o.LoraIds) {
		return true
	}

	return false
}

// SetLoraIds gets a reference to the given []string and assigns it to the LoraIds field.
func (o *NaomiHauteV1Input) SetLoraIds(v []string) {
	o.LoraIds = v
}

// GetPrompt returns the Prompt field value
func (o *NaomiHauteV1Input) GetPrompt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value
// and a boolean to check if the value has been set.
func (o *NaomiHauteV1Input) GetPromptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prompt, true
}

// SetPrompt sets field value
func (o *NaomiHauteV1Input) SetPrompt(v string) {
	o.Prompt = v
}

// GetCategory returns the Category field value
func (o *NaomiHauteV1Input) GetCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *NaomiHauteV1Input) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *NaomiHauteV1Input) SetCategory(v string) {
	o.Category = v
}

// GetGarmentImageId returns the GarmentImageId field value
func (o *NaomiHauteV1Input) GetGarmentImageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GarmentImageId
}

// GetGarmentImageIdOk returns a tuple with the GarmentImageId field value
// and a boolean to check if the value has been set.
func (o *NaomiHauteV1Input) GetGarmentImageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GarmentImageId, true
}

// SetGarmentImageId sets field value
func (o *NaomiHauteV1Input) SetGarmentImageId(v string) {
	o.GarmentImageId = v
}

// GetPoseId returns the PoseId field value
func (o *NaomiHauteV1Input) GetPoseId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PoseId
}

// GetPoseIdOk returns a tuple with the PoseId field value
// and a boolean to check if the value has been set.
func (o *NaomiHauteV1Input) GetPoseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoseId, true
}

// SetPoseId sets field value
func (o *NaomiHauteV1Input) SetPoseId(v string) {
	o.PoseId = v
}

// GetSeed returns the Seed field value
func (o *NaomiHauteV1Input) GetSeed() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Seed
}

// GetSeedOk returns a tuple with the Seed field value
// and a boolean to check if the value has been set.
func (o *NaomiHauteV1Input) GetSeedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Seed, true
}

// SetSeed sets field value
func (o *NaomiHauteV1Input) SetSeed(v float32) {
	o.Seed = v
}

// GetWidth returns the Width field value
func (o *NaomiHauteV1Input) GetWidth() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Width
}

// GetWidthOk returns a tuple with the Width field value
// and a boolean to check if the value has been set.
func (o *NaomiHauteV1Input) GetWidthOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Width, true
}

// SetWidth sets field value
func (o *NaomiHauteV1Input) SetWidth(v float32) {
	o.Width = v
}

// GetHeight returns the Height field value
func (o *NaomiHauteV1Input) GetHeight() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Height
}

// GetHeightOk returns a tuple with the Height field value
// and a boolean to check if the value has been set.
func (o *NaomiHauteV1Input) GetHeightOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Height, true
}

// SetHeight sets field value
func (o *NaomiHauteV1Input) SetHeight(v float32) {
	o.Height = v
}

// GetTextGuidanceScale returns the TextGuidanceScale field value if set, zero value otherwise.
func (o *NaomiHauteV1Input) GetTextGuidanceScale() float32 {
	if o == nil || IsNil(o.TextGuidanceScale) {
		var ret float32
		return ret
	}
	return *o.TextGuidanceScale
}

// GetTextGuidanceScaleOk returns a tuple with the TextGuidanceScale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NaomiHauteV1Input) GetTextGuidanceScaleOk() (*float32, bool) {
	if o == nil || IsNil(o.TextGuidanceScale) {
		return nil, false
	}
	return o.TextGuidanceScale, true
}

// HasTextGuidanceScale returns a boolean if a field has been set.
func (o *NaomiHauteV1Input) HasTextGuidanceScale() bool {
	if o != nil && !IsNil(o.TextGuidanceScale) {
		return true
	}

	return false
}

// SetTextGuidanceScale gets a reference to the given float32 and assigns it to the TextGuidanceScale field.
func (o *NaomiHauteV1Input) SetTextGuidanceScale(v float32) {
	o.TextGuidanceScale = &v
}

// GetImageGuidanceScale returns the ImageGuidanceScale field value if set, zero value otherwise.
func (o *NaomiHauteV1Input) GetImageGuidanceScale() float32 {
	if o == nil || IsNil(o.ImageGuidanceScale) {
		var ret float32
		return ret
	}
	return *o.ImageGuidanceScale
}

// GetImageGuidanceScaleOk returns a tuple with the ImageGuidanceScale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NaomiHauteV1Input) GetImageGuidanceScaleOk() (*float32, bool) {
	if o == nil || IsNil(o.ImageGuidanceScale) {
		return nil, false
	}
	return o.ImageGuidanceScale, true
}

// HasImageGuidanceScale returns a boolean if a field has been set.
func (o *NaomiHauteV1Input) HasImageGuidanceScale() bool {
	if o != nil && !IsNil(o.ImageGuidanceScale) {
		return true
	}

	return false
}

// SetImageGuidanceScale gets a reference to the given float32 and assigns it to the ImageGuidanceScale field.
func (o *NaomiHauteV1Input) SetImageGuidanceScale(v float32) {
	o.ImageGuidanceScale = &v
}

// GetNumInferenceSteps returns the NumInferenceSteps field value if set, zero value otherwise.
func (o *NaomiHauteV1Input) GetNumInferenceSteps() float32 {
	if o == nil || IsNil(o.NumInferenceSteps) {
		var ret float32
		return ret
	}
	return *o.NumInferenceSteps
}

// GetNumInferenceStepsOk returns a tuple with the NumInferenceSteps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NaomiHauteV1Input) GetNumInferenceStepsOk() (*float32, bool) {
	if o == nil || IsNil(o.NumInferenceSteps) {
		return nil, false
	}
	return o.NumInferenceSteps, true
}

// HasNumInferenceSteps returns a boolean if a field has been set.
func (o *NaomiHauteV1Input) HasNumInferenceSteps() bool {
	if o != nil && !IsNil(o.NumInferenceSteps) {
		return true
	}

	return false
}

// SetNumInferenceSteps gets a reference to the given float32 and assigns it to the NumInferenceSteps field.
func (o *NaomiHauteV1Input) SetNumInferenceSteps(v float32) {
	o.NumInferenceSteps = &v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *NaomiHauteV1Input) GetMode() string {
	if o == nil || IsNil(o.Mode) {
		var ret string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NaomiHauteV1Input) GetModeOk() (*string, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *NaomiHauteV1Input) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given string and assigns it to the Mode field.
func (o *NaomiHauteV1Input) SetMode(v string) {
	o.Mode = &v
}

func (o NaomiHauteV1Input) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NaomiHauteV1Input) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LoraIds) {
		toSerialize["loraIds"] = o.LoraIds
	}
	toSerialize["prompt"] = o.Prompt
	toSerialize["category"] = o.Category
	toSerialize["garmentImageId"] = o.GarmentImageId
	toSerialize["poseId"] = o.PoseId
	toSerialize["seed"] = o.Seed
	toSerialize["width"] = o.Width
	toSerialize["height"] = o.Height
	if !IsNil(o.TextGuidanceScale) {
		toSerialize["textGuidanceScale"] = o.TextGuidanceScale
	}
	if !IsNil(o.ImageGuidanceScale) {
		toSerialize["imageGuidanceScale"] = o.ImageGuidanceScale
	}
	if !IsNil(o.NumInferenceSteps) {
		toSerialize["numInferenceSteps"] = o.NumInferenceSteps
	}
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	return toSerialize, nil
}

func (o *NaomiHauteV1Input) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"prompt",
		"category",
		"garmentImageId",
		"poseId",
		"seed",
		"width",
		"height",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNaomiHauteV1Input := _NaomiHauteV1Input{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNaomiHauteV1Input)

	if err != nil {
		return err
	}

	*o = NaomiHauteV1Input(varNaomiHauteV1Input)

	return err
}

type NullableNaomiHauteV1Input struct {
	value *NaomiHauteV1Input
	isSet bool
}

func (v NullableNaomiHauteV1Input) Get() *NaomiHauteV1Input {
	return v.value
}

func (v *NullableNaomiHauteV1Input) Set(val *NaomiHauteV1Input) {
	v.value = val
	v.isSet = true
}

func (v NullableNaomiHauteV1Input) IsSet() bool {
	return v.isSet
}

func (v *NullableNaomiHauteV1Input) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNaomiHauteV1Input(val *NaomiHauteV1Input) *NullableNaomiHauteV1Input {
	return &NullableNaomiHauteV1Input{value: val, isSet: true}
}

func (v NullableNaomiHauteV1Input) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNaomiHauteV1Input) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


