/*
Hautech API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hautechapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImageRepresentationResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageRepresentationResponseDto{}

// ImageRepresentationResponseDto struct for ImageRepresentationResponseDto
type ImageRepresentationResponseDto struct {
	ImageId string `json:"imageId"`
	Type string `json:"type"`
	Url string `json:"url"`
}

type _ImageRepresentationResponseDto ImageRepresentationResponseDto

// NewImageRepresentationResponseDto instantiates a new ImageRepresentationResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageRepresentationResponseDto(imageId string, type_ string, url string) *ImageRepresentationResponseDto {
	this := ImageRepresentationResponseDto{}
	this.ImageId = imageId
	this.Type = type_
	this.Url = url
	return &this
}

// NewImageRepresentationResponseDtoWithDefaults instantiates a new ImageRepresentationResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageRepresentationResponseDtoWithDefaults() *ImageRepresentationResponseDto {
	this := ImageRepresentationResponseDto{}
	return &this
}

// GetImageId returns the ImageId field value
func (o *ImageRepresentationResponseDto) GetImageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value
// and a boolean to check if the value has been set.
func (o *ImageRepresentationResponseDto) GetImageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageId, true
}

// SetImageId sets field value
func (o *ImageRepresentationResponseDto) SetImageId(v string) {
	o.ImageId = v
}

// GetType returns the Type field value
func (o *ImageRepresentationResponseDto) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ImageRepresentationResponseDto) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ImageRepresentationResponseDto) SetType(v string) {
	o.Type = v
}

// GetUrl returns the Url field value
func (o *ImageRepresentationResponseDto) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ImageRepresentationResponseDto) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ImageRepresentationResponseDto) SetUrl(v string) {
	o.Url = v
}

func (o ImageRepresentationResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageRepresentationResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["imageId"] = o.ImageId
	toSerialize["type"] = o.Type
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *ImageRepresentationResponseDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"imageId",
		"type",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImageRepresentationResponseDto := _ImageRepresentationResponseDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImageRepresentationResponseDto)

	if err != nil {
		return err
	}

	*o = ImageRepresentationResponseDto(varImageRepresentationResponseDto)

	return err
}

type NullableImageRepresentationResponseDto struct {
	value *ImageRepresentationResponseDto
	isSet bool
}

func (v NullableImageRepresentationResponseDto) Get() *ImageRepresentationResponseDto {
	return v.value
}

func (v *NullableImageRepresentationResponseDto) Set(val *ImageRepresentationResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableImageRepresentationResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableImageRepresentationResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageRepresentationResponseDto(val *ImageRepresentationResponseDto) *NullableImageRepresentationResponseDto {
	return &NullableImageRepresentationResponseDto{value: val, isSet: true}
}

func (v NullableImageRepresentationResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageRepresentationResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


