/*
Hautech API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hautechapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ModifyAccessParamsDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModifyAccessParamsDto{}

// ModifyAccessParamsDto struct for ModifyAccessParamsDto
type ModifyAccessParamsDto struct {
	PrincipalType string `json:"principalType"`
	PrincipalId string `json:"principalId"`
	ResourceId string `json:"resourceId"`
	Access string `json:"access"`
}

type _ModifyAccessParamsDto ModifyAccessParamsDto

// NewModifyAccessParamsDto instantiates a new ModifyAccessParamsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModifyAccessParamsDto(principalType string, principalId string, resourceId string, access string) *ModifyAccessParamsDto {
	this := ModifyAccessParamsDto{}
	this.PrincipalType = principalType
	this.PrincipalId = principalId
	this.ResourceId = resourceId
	this.Access = access
	return &this
}

// NewModifyAccessParamsDtoWithDefaults instantiates a new ModifyAccessParamsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModifyAccessParamsDtoWithDefaults() *ModifyAccessParamsDto {
	this := ModifyAccessParamsDto{}
	return &this
}

// GetPrincipalType returns the PrincipalType field value
func (o *ModifyAccessParamsDto) GetPrincipalType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrincipalType
}

// GetPrincipalTypeOk returns a tuple with the PrincipalType field value
// and a boolean to check if the value has been set.
func (o *ModifyAccessParamsDto) GetPrincipalTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrincipalType, true
}

// SetPrincipalType sets field value
func (o *ModifyAccessParamsDto) SetPrincipalType(v string) {
	o.PrincipalType = v
}

// GetPrincipalId returns the PrincipalId field value
func (o *ModifyAccessParamsDto) GetPrincipalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrincipalId
}

// GetPrincipalIdOk returns a tuple with the PrincipalId field value
// and a boolean to check if the value has been set.
func (o *ModifyAccessParamsDto) GetPrincipalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrincipalId, true
}

// SetPrincipalId sets field value
func (o *ModifyAccessParamsDto) SetPrincipalId(v string) {
	o.PrincipalId = v
}

// GetResourceId returns the ResourceId field value
func (o *ModifyAccessParamsDto) GetResourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value
// and a boolean to check if the value has been set.
func (o *ModifyAccessParamsDto) GetResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceId, true
}

// SetResourceId sets field value
func (o *ModifyAccessParamsDto) SetResourceId(v string) {
	o.ResourceId = v
}

// GetAccess returns the Access field value
func (o *ModifyAccessParamsDto) GetAccess() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Access
}

// GetAccessOk returns a tuple with the Access field value
// and a boolean to check if the value has been set.
func (o *ModifyAccessParamsDto) GetAccessOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Access, true
}

// SetAccess sets field value
func (o *ModifyAccessParamsDto) SetAccess(v string) {
	o.Access = v
}

func (o ModifyAccessParamsDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModifyAccessParamsDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["principalType"] = o.PrincipalType
	toSerialize["principalId"] = o.PrincipalId
	toSerialize["resourceId"] = o.ResourceId
	toSerialize["access"] = o.Access
	return toSerialize, nil
}

func (o *ModifyAccessParamsDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"principalType",
		"principalId",
		"resourceId",
		"access",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModifyAccessParamsDto := _ModifyAccessParamsDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModifyAccessParamsDto)

	if err != nil {
		return err
	}

	*o = ModifyAccessParamsDto(varModifyAccessParamsDto)

	return err
}

type NullableModifyAccessParamsDto struct {
	value *ModifyAccessParamsDto
	isSet bool
}

func (v NullableModifyAccessParamsDto) Get() *ModifyAccessParamsDto {
	return v.value
}

func (v *NullableModifyAccessParamsDto) Set(val *ModifyAccessParamsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableModifyAccessParamsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableModifyAccessParamsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModifyAccessParamsDto(val *ModifyAccessParamsDto) *NullableModifyAccessParamsDto {
	return &NullableModifyAccessParamsDto{value: val, isSet: true}
}

func (v NullableModifyAccessParamsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModifyAccessParamsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


