name: Release

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          skip-github-pull-request: true
